### ISSUE TITLE
demo popup calendar generates invalid dates

### ISSUE THREAD

**Issue by linuxcaffe** [DavidBadura/doThings#20]
In trying the demo,  attempting to set a due-date, I get an error message is generated "Not a valid date" and the new or modified task can not be saved.

**Comment by DavidBadura** [comment]
do you also set a time or only a date? see #8

**Comment by linuxcaffe** [comment]
ahhh.. no, I hadn't! this is a dupe, then!

**Comment by DavidBadura** [comment]
btw. the problem is solved :wink:
