### ISSUE TITLE
Install and Run

### ISSUE THREAD

**Issue by bserrao** [DavidBadura/doThings#34]
Hey, 
I'm having some trouble installing and running this app. 
Could you provide more instructions?

I'm using NGINX has a web server, and did the install in the server root /srv/http/doThings/
I'm trying to run http://localhost/web/app.php  is this correct? When i hit enter the address changes to http://localhost/web/app.php/login and i get a 404 (Not Found).

What am i doing wrong?
Thanks a lot

**Comment by tolry** [comment]
Hi @bserrao 

everything is still very much alpha around here, so the installation process is not really polished so far.

doThings is using Symfony Standard Distribution as a basis, so if you have any experience in setting up symfony application, you can apply that knowledge here.

I would suggest starting with the symfony recommended nginx configuration http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx

The document root should always be the "web" folder, never the one above that (security reasons) and  the var folder needs to be writable by the nginx / php5-fpm user.

If you are running a local dev installation you might want to use the dev mode by calling app_dev.php, to get better error messages.

I hope this helps a bit.

**Comment by bserrao** [comment]
Thanks a lot for the quick feedback :)
I've managed to run, and login with your precious help. Still facing internal server error after login, but i'm going to do a bit of debug now.

**Comment by DavidBadura** [comment]
you get still 404? most likely in this case your nginx config is wrong.

**Comment by DavidBadura** [comment]
btw. if you can wait i will add an installation instructions this weekend :wink:

**Comment by bserrao** [comment]
Hey, 
Sorry for the late feedback, but only now i could come back to this...

I'm getting this error now when running php app/console :

"Could not decode JSON, malformed UTF-8 characters (incorrectly encoded?)
500 Internal Server Error - RuntimeException"

**Comment by DavidBadura** [comment]
you run `php app/console :` ?

**Comment by DavidBadura** [comment]
what you get if you run `php app/console`?

**Comment by DavidBadura** [comment]
oh, i understand... hmm... let me think about it.

**Comment by DavidBadura** [comment]
can you try it with `php app/console -vvv` and dump the result here? thank you! :)

**Comment by bserrao** [comment]
I've tried to run with php app/console in order to get more feedback to the issue...

 RUN  '/usr/bin/php' '-S' '10.176.19.138:8000' '/srv/http/doThings/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php'
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55630 [500]: /list/
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55629 [200]: /bundles/framework/css/structure.css
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55628 [200]: /bundles/framework/css/body.css
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55631 [200]: /bundles/framework/css/exception.css
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55633 [200]: /favicon.ico
  ERR  [Mon Jul  6 15:05:57 2015] 10.176.19.221:55632 [200]: /_wdt/713a53

In the WEB page that opens i have this:
Stack Trace
in vendor/jms/serializer/src/JMS/Serializer/JsonDeserializationVisitor.php at line 46   -
                throw new RuntimeException('Could not decode JSON, syntax error - malformed JSON.');
            case JSON_ERROR_UTF8:
                throw new RuntimeException('Could not decode JSON, malformed UTF-8 characters (incorrectly encoded?)');
            default:
                throw new RuntimeException('Could not decode JSON.');

**Comment by DavidBadura** [comment]
ah... i think, i know the problem.

can you change in `app/config/parameters.yml` following lines?

```
taskwarrior_taskrc: /absolute/path/to/.taskrc
taskwarrior_data: /absolute/path/to/.task
```

php don't support "~" :-( see https://github.com/webmozart/path-util/issues/10 and https://github.com/webmozart/path-util/pull/11. if it is merged, then it should work.

i will create also an issue in my lib to discover this problem.

you should make sure that it is readable and writeable.

thank you for debugging!

**Comment by bserrao** [comment]
OK, it's working when i run php app/console ...
But it's returning 500 Internal server error from NGINX server.
I'll do some more debugging...

Again, thanks a lot for all the help provided.

**Comment by bserrao** [comment]
Ok, i've found what's wrong, but i can't find where the app is reading the info...
Below is the error:
[2015-07-07 11:31:19] request.CRITICAL: Uncaught PHP Exception DavidBadura\Taskwarrior\Exception\CommandException: "Could not write to '/srv/http/tasks/.taskrc'." at /srv/http/doThings/vendor/davidbadura/taskwarrior/src/Taskwarrior.php line 202 {"exception":"[object](DavidBadura\Taskwarrior\Exception\CommandException%28code: 2%29: Could not write to '/srv/http/tasks/.taskrc'. at /srv/http/doThings/vendor/davidbadura/taskwarrior/src/Taskwarrior.php:202)"} []

It's trying to open /srv/http/tasks/.taskrc, but the path i have configured now in parameter.yml is parameters:
    taskwarrior_taskrc: /srv/tasks/.taskrc
    taskwarrior_data: /srv/tasks/.task

The app stored the previous path somewere, and i can't find were...

**Comment by tolry** [comment]
When you are using app.php to access the application, configuration data is cached.

You can either access the application using app_dev.php (where almost no caching is done) or you can clear the cache for the production environment by

``` sh
sudo -u www-data php app/console cache:clear --env=prod
```

**Comment by DavidBadura** [comment]
@bserrao did you get it? :)

**Comment by bserrao** [comment]
Yep, all set. I've been using it.
It has a few bugs though, but i haven't flag them yet, since it's still a project in a very early development.

**Comment by DavidBadura** [comment]
if you find any bugs, can you create issues please? that would help me a lot :-)
